# Generated by Django 3.2.9 on 2021-11-12 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateField(default=datetime.datetime(2021, 11, 12, 14, 53, 43, 983194, tzinfo=utc))),
                ('is_superuser', models.BooleanField()),
            ],
        ),
    ]
