# Generated by Django 3.2.9 on 2021-11-12 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRUDUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(default=datetime.datetime(2021, 11, 12, 16, 51, 48, 72790, tzinfo=utc))),
                ('is_superuser', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
