# Generated by Django 3.2.9 on 2021-11-12 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211112_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruduser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cruduser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 16, 52, 59, 8226, tzinfo=utc)),
        ),
    ]
