# Generated by Django 3.2.9 on 2021-11-12 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211112_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruduser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 16, 53, 24, 51378, tzinfo=utc)),
        ),
    ]
