# Generated by Django 3.2.9 on 2021-11-13 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cruduser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruduser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cruduser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 0, 0, 0, 766182)),
        ),
    ]
