# Generated by Django 3.2.9 on 2021-11-15 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211113_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruduser',
            name='username',
        ),
    ]
