# Generated by Django 3.2.9 on 2021-11-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211115_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruduser',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
