# Generated by Django 3.2.9 on 2021-11-15 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211115_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(default=datetime.datetime(2021, 11, 11, 0, 0, 0, 766182))),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='CRUDUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
