# Generated by Django 3.2.9 on 2021-11-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211115_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeluser',
            name='password',
            field=models.CharField(default=0, max_length=128, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modeluser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='modeluser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
