# Generated by Django 3.2.9 on 2021-11-15 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211115_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeluser',
            name='authtoken',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modeluser',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Не правильно задан пароль', regex='^(?=.*[A-Z])(?=.*\\d).{8,}$')], verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='modeluser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Username'),
        ),
    ]
