# Generated by Django 3.2.9 on 2021-11-15 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_modeluser_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeluser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 0, 31, 57, 478111)),
        ),
    ]
